In [1]:
# Estimate pi using MC methods, parallelized with MPI
import numpy as np

In [18]:
# Generate random points in quadrant of a square/circle.
# Points (x,y) whose distance is normalized to 1 will be on the arc.
# Greater than 1 and less than sqrt(2) will be outside the circle in the square. 
# Comparing samples of points will allow us to find the ratio 1/pi, and thus pi.

def generate_points(num_pairs):
    return np.random.uniform(high=np.sqrt(2), size=(num_pairs,2))


In [19]:
points = generate_points(100)

In [25]:
# Calculate for each point whether it is inside or outside the arc.
def calc_lengths(pairs):
    return np.array([np.linalg.norm(i) for i in pairs])

In [26]:
calc_lengths(points)

array([0.95422289, 1.44444342, 0.82438491, 1.2211868 , 1.89015655,
       1.56802238, 0.80729582, 1.28475209, 1.32062115, 1.00291293,
       0.48509483, 1.23929965, 1.07837497, 1.15138045, 1.16694227,
       1.38011196, 0.1831338 , 0.02583349, 1.49242254, 1.59104283,
       1.81486025, 1.05959693, 1.23473881, 1.4255419 , 0.92223934,
       1.62733335, 1.34870399, 1.24479434, 1.37614766, 1.41773741,
       1.19632588, 0.93439946, 0.96933637, 1.5486788 , 1.20431452,
       0.30681569, 1.25672726, 1.22795401, 0.41076143, 1.27185713,
       0.938687  , 1.06929099, 1.6909625 , 1.72555323, 0.5776439 ,
       1.17708625, 1.30807022, 1.70156363, 1.48633102, 0.33169715,
       1.04762303, 1.42724812, 1.38175514, 0.58639075, 1.21127396,
       1.10954629, 1.2117007 , 1.04379269, 0.81589591, 1.24591978,
       1.2036558 , 1.07419507, 0.97470197, 1.09969175, 1.24995019,
       1.18336737, 1.40554217, 1.06480641, 1.16734259, 1.10377078,
       1.32834484, 1.56607561, 0.91070192, 1.1009146 , 1.52622

In [13]:
a = np.random.uniform(high=np.sqrt(2), size=(2,2))
a

array([[0.08085825, 0.5071047 ],
       [0.7051613 , 0.73357533]])

In [21]:
a

array([[0.08085825, 0.5071047 ],
       [0.7051613 , 0.73357533]])

In [22]:
[np.linalg.norm(i) for i in a]

[0.51351069141708, 1.0175388073118494]

In [24]:
np.sqrt(0.08085825**2 + 0.5071047**2)

0.5135106944895622